### ISSUE TITLE
Use Grove Ultrasonic in Nodejs and Python

### ISSUE THREAD

**Issue by ghost** [Seeed-Studio/Grove_Ultrasonic_Ranger#1]
Is there any way to use the sensor with python and nodejs as the majority of sensors offer, if it is the case could you please provide a simple example.
Thanks in advance

**Comment by lanselambor** [comment]
Of course there are some HW platforms use ultrasonic with python and nodejs like Beagleboard raspberrypi(GrovePi+) Intel Edison.
