### ISSUE TITLE
[Feature] Wants the grove ultrasonic ranger's library to support more than 1 ultrasonic ranger.

### ISSUE THREAD

**Issue by Coderisnice** [Seeed-Studio/Grove_Ultrasonic_Ranger#10]
---
**_### Feature Request_**

Name: YH

Feature request about: Wants library to support more than 1 ultrasonic Ranger

Sensor title: Grove Ultrasonic Ranger

**Is your feature request related to a problem?**

Yes, I wanted to do a project. It needs more than 1 ultrasonic ranger, but the library could not support them.

**Describe the solution you'd like**

Please add some functions to let the library support more than 1 ultrasonic ranger.

_Hopefully, you will add this feature as soon as possible.

Thanks._

**Comment by Coderisnice** [comment]
If anybody knows the solution without needing them to change the library, please directly tell me at the comments bar.

**Comment by Coderisnice** [comment]
HI?

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

We will consider your request.

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
