### ISSUE TITLE
"ultrasonic.MeasureInMillimeters();" not working

### ISSUE THREAD

**Issue by BigSmoke908** [Seeed-Studio/Grove_Ultrasonic_Ranger#7]
if i take a variable and give it the value "ultrasonic.MeasureInMillimeters();" the arduino ide says, that this does not exist (exact error message below). I have the library installed and other things like 
"ultrasonic.MeasureInCentimeters();" work just fine. I am using version 1.0.0 of this library.

Complete Error Message:
Arduino: 1.8.15 (Windows 10), Board: "Arduino Uno"
C:\Users\PC\Desktop\sketch_jul06a\sketch_jul06a.ino: In function 'void loop()':

sketch_jul06a:42:28: error: 'class Ultrasonic' has no member named 'MeasureInMillimeters'; did you mean 'MeasureInCentimeters'?

   centimeters = ultrasonic.MeasureInMillimeters();

                            ^~~~~~~~~~~~~~~~~~~~

                            MeasureInCentimeters

exit status 1

'class Ultrasonic' has no member named 'MeasureInMillimeters'; did you mean 'MeasureInCentimeters'?

Note for further questions: i am not that active on GitHub, if you try to contact me, please use my discord (Ken Rosenberg#9127)

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Does this problem still exist? If so, can you provide a reproducible environment?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
