### ISSUE TITLE
Is there any way to High sampling rate without no obstacles

### ISSUE THREAD

**Issue by uecken** [Seeed-Studio/Grove_Ultrasonic_Ranger#9]
I tried "duration(10000)", but this function only return 0 if timeout occurs.
Now, Ultrasonic transmitting frequency is not so high in case no obstacles, that's is about 32ms.

![image](https://user-images.githubusercontent.com/5786149/196358973-bb52c263-e6c3-47c0-917d-94bbf03f5ce0.png)

Is there any way to get high sampling rate?
I know that previous transmitted ultrasonic affects the next measurement.

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
